[Fix] local

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,73 +1,73 @@
-name: CD
+# name: CD
 
-on:
-  workflow_run:
-    workflows: ["CI"]
-    types:
-      - completed
+# on:
+#   workflow_run:
+#     workflows: ["CI"]
+#     types:
+#       - completed
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
 
-      - name: Copy Docker Compose files via SSH
-        uses: appleboy/scp-action@v0.1.3
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          source: "nginx.conf,docker-compose.yml,docker-compose.prod.yml"
-          target: "/home/${{ secrets.SERVER_USER }}/banada_backend/"
+#       - name: Copy Docker Compose files via SSH
+#         uses: appleboy/scp-action@v0.1.3
+#         with:
+#           host: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USER }}
+#           key: ${{ secrets.SERVER_SSH_KEY }}
+#           source: "nginx.conf,docker-compose.yml,docker-compose.prod.yml"
+#           target: "/home/${{ secrets.SERVER_USER }}/banada_backend/"
 
-      - name: Create .env file on server
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          script: |
-            echo "${{ secrets.ENV_VARS }}" > /home/${{ secrets.SERVER_USER }}/banada_backend/.env
+#       - name: Create .env file on server
+#         uses: appleboy/ssh-action@v0.1.6
+#         with:
+#           host: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USER }}
+#           key: ${{ secrets.SERVER_SSH_KEY }}
+#           script: |
+#             echo "${{ secrets.ENV_VARS }}" > /home/${{ secrets.SERVER_USER }}/banada_backend/.env
 
-      - name: Install Docker and Docker Compose if needed
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          script: |
-            if ! command -v docker &> /dev/null
-            then
-              echo "Docker not found. Installing Docker..."
-              curl -fsSL https://get.docker.com -o get-docker.sh
-              sh get-docker.sh
-              sudo usermod -aG docker $USER
-              newgrp docker
-              rm get-docker.sh
-            else
-              echo "Docker is already installed."
-            fi
+#       - name: Install Docker and Docker Compose if needed
+#         uses: appleboy/ssh-action@v0.1.6
+#         with:
+#           host: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USER }}
+#           key: ${{ secrets.SERVER_SSH_KEY }}
+#           script: |
+#             if ! command -v docker &> /dev/null
+#             then
+#               echo "Docker not found. Installing Docker..."
+#               curl -fsSL https://get.docker.com -o get-docker.sh
+#               sh get-docker.sh
+#               sudo usermod -aG docker $USER
+#               newgrp docker
+#               rm get-docker.sh
+#             else
+#               echo "Docker is already installed."
+#             fi
 
-            if ! command -v docker-compose &> /dev/null
-            then
-              echo "Docker Compose not found. Installing Docker Compose..."
-              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-              sudo chmod +x /usr/local/bin/docker-compose
-            else
-              echo "Docker Compose is already installed."
-            fi
+#             if ! command -v docker-compose &> /dev/null
+#             then
+#               echo "Docker Compose not found. Installing Docker Compose..."
+#               sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+#               sudo chmod +x /usr/local/bin/docker-compose
+#             else
+#               echo "Docker Compose is already installed."
+#             fi
 
-      - name: Deploy to server via SSH
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          script: |
-            cd /home/${{ secrets.SERVER_USER }}/banada_backend
-            docker-compose down --remove-orphans
-            docker-compose -f docker-compose.prod.yml pull
-            docker-compose -f docker-compose.prod.yml up -d
+#       - name: Deploy to server via SSH
+#         uses: appleboy/ssh-action@v0.1.6
+#         with:
+#           host: ${{ secrets.SERVER_HOST }}
+#           username: ${{ secrets.SERVER_USER }}
+#           key: ${{ secrets.SERVER_SSH_KEY }}
+#           script: |
+#             cd /home/${{ secrets.SERVER_USER }}/banada_backend
+#             docker-compose down --remove-orphans
+#             docker-compose -f docker-compose.prod.yml pull
+#             docker-compose -f docker-compose.prod.yml up -d
